application:
  name: 'registry'

worker:
  id: 'registry'
  host: '127.0.0.1'
  environment: 'local'
  environment-sequence: 'local'

matata:
  registry:
    host: '127.0.0.1'
    port: 8090
    protocol: 2
    environment: 'local'

server:
  http:
    port: 8090