name: Maven Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: euleros-2.10.1
    steps:
    - uses: checkout-action@0.0.1
    - name: Setup JDK 
      uses: setup-java@0.0.1
      with:
        java-version: '17'
    - name: Build with Maven
      run: cd repo_workspace && mvn -B package --file pom.xml